// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kopzrbvrcgknjgoyewxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvcHpyYnZyY2drbmpnb3lld3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNDc4ODMsImV4cCI6MjA3NjcyMzg4M30.e1e38gAUc8Te0T5XaYEBHe4k_8aUq2d8EqBD-VhsSz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});